name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "stage or prod"
        required: true
        options:
         - stage
         - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your EKS cluster region

    - name: Set up kubectl
      run: |
        aws eks update-kubeconfig --name wonderful-jazz-ant --region us-east-1

    - name: Get pods
      run: |
        kubectl get pods    

    - name: Get nodes
      run: |
        kubectl get nodes
        ls -l

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/${{github.event.inputs.environment}}/

    # - name: Verify deployment
    #   run: |
    #     kubectl rollout status deployment/my-app
