name: Restart Azure App Service

on:
  workflow_dispatch:  # Allows manual triggering of workflow
    inputs:
      resource_group:
          description: "Resource group name"
          type: choice
          required: true
          options:
            - RG1
          default: "RG1"
      appservice_name:
          description: "app service name"
          required: true
          default: "app"
      action:
        type: choice
        description: "start or stop"
        required: true
        options:
         - start
         - stop
        default: "get"          


jobs:
  restart-app-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: login to Azure 
      run: az login --service-principal --username=fa1085d1-a654-4325-8a45-6d5b9fe0534d  -p="cND8Q~oYKod4L0RPwxrNEKjCSbRiqLsqt8ZItdB7" --tenant=64ceb8ab-f04f-477d-8057-7dfdacb83dcb 
        
    - name: stop App Service
      run: az webapp ${{github.event.inputs.action}} --name ${{github.event.inputs.appservice_name}} --resource-group ${{github.event.inputs.resource_group}}

    # - name: login to Azure and stop App Service
    #   run: |
    #     az login --service-principal --username  -p= --tenant 
    #     az webapp stop --name ${{github.event.inputs.appservice_name}} --resource-group ${{github.event.inputs.resource_group}}  
