name: Azure App Service

on:
  workflow_dispatch:  # Allows manual triggering of workflow
    inputs:
      resource_group:
          description: "Resource group name"
          type: choice
          required: true
          options:
            - RG1
            - TEST03212025_group
          default: "RG1"
      appservice_name:
          description: "app service name"
          required: true
          default: "app"
      action:
        type: choice
        description: "start or stop"
        required: true
        options:
         - start
         - stop
         - show
        default: "show"          


jobs:
  restart-app-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: login to Azure 
      run: az login --service-principal --username=7abfcd5a-ffc8-40eb-b59d-488d68ebf6c0  -p="oj38Q~aARtXO0finllTACSnFqZbtMBanPUOvsazX" --tenant=44e4dc69-618c-4f06-bfe6-116d949e0873 
        
    - name: ${{github.event.inputs.action}} App Service
      run: az webapp ${{github.event.inputs.action}} --name ${{github.event.inputs.appservice_name}} --resource-group ${{github.event.inputs.resource_group}}

    - name: config App Service on East region
      run: |
        az webapp config appsettings set --resource-group ${{github.event.inputs.resource_group}} --name test03312025 --settings key1=valuenewes
        az webapp config appsettings set --resource-group ${{github.event.inputs.resource_group}} --name test03312026 --settings key1=valuenewes

    - name: config App Service on West region
      run: |
        az webapp config appsettings set --resource-group ${{github.event.inputs.resource_group}} --name test03312025 --settings key1=valuenewes
        az webapp config appsettings set --resource-group ${{github.event.inputs.resource_group}} --name test03312026 --settings key1=valuenewes
        
    
    # - name: copy script
    #   run: az webapp deploy --name test05032024 --resource-group RG1 --src-path="myscript.sh" --type="static" --target-path="myinit.sh"

    # - name: Run Shell Script
    #   run: |
    #     az webapp ssh --resource-group RG1 --name test05032024



        
    # - name: Create remote connection to Azure App Service
    #   run: |
    #     az webapp create-remote-connection --name test05032024 --resource-group RG1 --output json > connection.json
    #     sleep 15
    #     echo "::set-output name=connectionString::$(jq -r .connectionString connection.json)"

    # - name: Copy script to Azure App Service
    #   run: |
    #     scp -P $(echo ${{ steps.connection.outputs.connectionString }} | sed -n 's/.*:\([0-9]\{1,\}\).*/\1/p') -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null myscript.sh root@127.0.0.1:/home/site/wwwroot/
        
    # - name: Copy script to Azure App Service
    #   run: |
    #     az webapp create-remote-connection --name test05032024 --resource-group RG1 &
    #     sleep 15
     #   scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null myscript.sh root@127.0.0.1:/home/site/wwwroot/

    # - name: Run script on Azure App Service
    #   run: |
    #     az webapp ssh --name ${{ secrets.AZURE_APP_SERVICE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --command "bash /home/site/wwwroot/myscript.sh"

    # - name: Remove Folder
    #   run: |
    #     az webapp deployment source delete --name ${{github.event.inputs.appservice_name}} --resource-group ${{github.event.inputs.resource_group}} --path /Home/dyno
